//En 530.421

#define sensor A0 // Sharp IR GP2Y0A41SK0F (4-30cm, analog)

void setup() {
  Serial.begin(9600); // start the serial port
}

void loop() {
  float volts = analogRead(sensor)*0.0048828125;  // value from sensor * (5/1024)
  Serial.println(volts); // print out voltage generated by IR sensor
  delay(200); // small delay
}
